### ISSUE TITLE
Create classes

### ISSUE THREAD

**Issue by Codo-Baggins** [Codo-Baggins/whats-cookin#1]
In order to implement the desired functionality of our application, I believe it would be beneficial to construct a class for the User, Pantry, and Recipe. We will want the following:

User
Constructor will have keys of: id, name, pantry, favoriteRecipes, recipesToCook

Methods will include: addToFavorites, removeFromFavorites, addToRecipesToCook, filterUserRecipes, searchUserRecipes

Recipe
Constructor will have keys of: id, image, ingredients, instructions, name, and tags

Methods will include: filterRecipesByTag, searchRecipesByIngredient, calculateRecipeCost, returnInstructions
Pantry
Constructor will have keys of: stockedIngredients

Methods will include: checkIngredientRequirement, returnMissingIngredients, removeIngredients

**Comment by atownse** [comment]
Great description, it might be better to break these into three separate issues since we'll be working on them at different times

**Comment by Codo-Baggins** [comment]
I copied our class structure, after discussing it with my group, I realize that there is too much of the "how".

**Comment by Codo-Baggins** [comment]
This issue is too discriptive.
